"""add role for user model

Revision ID: 8cb01f45a04d
Revises: f03ff3a53ca7
Create Date: 2024-10-04 23:58:14.744749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cb01f45a04d'
down_revision: Union[str, None] = 'f03ff3a53ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum('user', 'recruiter', 'director', 'admin', name='user_role')
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', postgresql.ENUM('user', 'recruiter', 'director', 'admin', name='user_role'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
