"""Delete avatar_filename from User model

Revision ID: 0987680ab342
Revises: 616c534beae7
Create Date: 2024-10-05 15:13:18.091270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0987680ab342'
down_revision: Union[str, None] = '616c534beae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
