"""Final version

Revision ID: 21dd39acd73b
Revises: 8cc771045065
Create Date: 2024-10-06 00:37:49.046734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21dd39acd73b'
down_revision: Union[str, None] = '8cc771045065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('candidates', sa.Column('recruiter_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'recruiter_description')
    op.drop_column('candidates', 'updated_at')
    # ### end Alembic commands ###
