"""Replacing date and time with one column that combines both date and time.

Revision ID: 81359903576a
Revises: 0987680ab342
Create Date: 2024-10-05 16:32:33.103796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81359903576a'
down_revision: Union[str, None] = '0987680ab342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('interviews', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('interviews', 'date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
