"""Renamed date to datetime in Interview model

Revision ID: 8cc771045065
Revises: 28587c58824e
Create Date: 2024-10-05 18:30:12.005642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cc771045065'
down_revision: Union[str, None] = '28587c58824e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('datetime', sa.TIMESTAMP(), nullable=False))
    op.drop_column('interviews', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('interviews', 'datetime')
    # ### end Alembic commands ###
