"""Changed the name of the vacancy owner column

Revision ID: e06c72b684e3
Revises: 81359903576a
Create Date: 2024-10-05 16:35:28.168456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06c72b684e3'
down_revision: Union[str, None] = '81359903576a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('creator_username', sa.String(), nullable=False))
    op.drop_constraint('vacancies_recruiter_username_fkey', 'vacancies', type_='foreignkey')
    op.create_foreign_key(None, 'vacancies', 'users', ['creator_username'], ['username'])
    op.drop_column('vacancies', 'recruiter_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('recruiter_username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.create_foreign_key('vacancies_recruiter_username_fkey', 'vacancies', 'users', ['recruiter_username'], ['username'])
    op.drop_column('vacancies', 'creator_username')
    # ### end Alembic commands ###
